name: Linter Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, dom, pdo, pdo_mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader

    - name: Run Laravel Pint
      uses: sergotail/laravel-pint-action@main  # or main if v1 doesn't work

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install Node.js dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint
